In [ ]:
import torch
from torch import nn # nn neural network building block
import numpy as np
import matplotlib.pyplot as plt


torch.__version__

'2.11.0+cpu'

In [ ]:
#know parameters

weight = 0.7
bias = 0.3


#create
start = 0
end = 1
step = 0.02

X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias



In [ ]:
train_set = int(0.8 * len(X))
X_train , y_train = X[:train_set] , y[:train_set]
X_test , y_test = X[train_set: ] , y[train_set: ]

#BUILDING A MODEL
  

In [ ]:
class LinearRegressionModel(nn.Module): # <--- this is subclass , this give access/ inherid all functionality from nn.Module
  def __init__(self): # <--- This is the constructor. It's the method that runs automatically whenever you create a new instance of the class.
    super().__init__()# <---- gives you access to the parent class (nn.Module)
    self.weights = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))

    self.bias = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))

  def forward(self, x:torch.Tensor) -> torch.Tensor: # x is the input data, "-->" means this function is expected to return a torch.Tensor.
      return self.weights * x + self.bias # linear regression


In [ ]:
model_1 = LinearRegressionModel()
model_1.state_dict()

OrderedDict([('weights', tensor([0.3784])), ('bias', tensor([0.1123]))])

In [ ]:
X_test

tensor([[0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

In [ ]:
with torch.inference_mode():
  y_pre = model_1(X_test)

In [ ]:
y_pre

tensor([[0.4150],
        [0.4226],
        [0.4301],
        [0.4377],
        [0.4453],
        [0.4528],
        [0.4604],
        [0.4680],
        [0.4755],
        [0.4831]])

In [ ]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [ ]:
loss = nn.L1Loss()